apiVersion: v2
name: ghes-schedule-scanner
description: A Helm chart for deploying the GHES Schedule Scanner
deprecated: false
type: application
version: 0.5.0
appVersion: 0.5.0

keywords:
  - github
  - enterprise
  - scanner
  - schedule
  - scheduled-workflow
  - cronjob
home: https://github.com/younsl/ghes-schedule-scanner
sources:
  - https://github.com/younsl/ghes-schedule-scanner

maintainers:
  - name: younsl
    email: cysl@kakao.com
    url: https://github.com/younsl
  - name: ddukbg
    email: wowrebong@gmail.com
    url: https://github.com/ddukbg

dependencies: []

annotations:
  artifacthub.io/package-type: helm
  artifacthub.io/alternate-name: ghes-schedule-scanner
  artifacthub.io/display-name: GHES Schedule Scanner
  artifacthub.io/repository: younsl/ghes-schedule-scanner
  artifacthub.io/license: MIT
  artifacthub.io/operator: "false"
