name: Labeler
run-name: "🔖 [younsl/gss] Label pull request #${{ github.event.pull_request.number }} from ${{ github.head_ref }}"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        id: checkout

      - name: Attach labels
        uses: actions/labeler@v5
        id: label
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
          dot: true